# https://esphome.io/components/esphome
esphome:
  name: '${node_name}'
  # https://github.com/esphome/feature-requests/issues/2476
  # https://community.home-assistant.io/t/how-is-friendly-name-supposed-to-behave/542570/9
  # see more info at https://github.com/jzucker2/goober/blob/master/notes/ESPHOME.md
  # friendly_name: ${friendly_name}
  # name_add_mac_suffix: false
  area: ${area}
  comment: ${comment}
  project: !include default_project.yaml
  # Workaround for Button (GPIO39) randomly triggering
  # Increases power usage slightly (~1mA)
  # https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/api-reference/peripherals/adc.html#_CPPv412adc1_get_raw14adc1_channel_t
  includes:
    - common/adc_driver.h
  on_boot:
    then:
      - lambda: "adc_power_acquire();"
