# https://github.com/esphome/esphome/pull/9941
external_components:
  - source: github://pr#9941
    components: [prometheus]
    refresh: 0s

# https://esphome.io/components/prometheus.html
# Activates prometheus /metrics endpoint
prometheus:
  include_internal: true
