# Real prometheus datetime pr: https://github.com/esphome/esphome/pull/9941
# Temp hotfix for dev and prod divergence: https://github.com/esphome/esphome/pull/13193
external_components:
  - source: github://pr#13193
    components: [prometheus]
    refresh: 0s

# https://esphome.io/components/prometheus.html
# Activates prometheus /metrics endpoint
prometheus:
  include_internal: true
