# https://devices.esphome.io/devices/M5Stack-Dial
esphome:
  name: ${node_name}
  # for more on friendly_name issues, see https://github.com/jzucker2/goober/blob/master/notes/ESPHOME.md
  # friendly_name: ${friendly_name}
  area: ${area}
  comment: ${comment}
  project: !include ../default_project.yaml
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - bm8563.read_time:
      - script.execute: dial_lights_boot_up_script
      - logger.log: 'Done with boot up lights script'
